// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"elsenova/models"
)

func newCustomCommand(db *gorm.DB, opts ...gen.DOOption) customCommand {
	_customCommand := customCommand{}

	_customCommand.customCommandDo.UseDB(db, opts...)
	_customCommand.customCommandDo.UseModel(&models.CustomCommand{})

	tableName := _customCommand.customCommandDo.TableName()
	_customCommand.ALL = field.NewAsterisk(tableName)
	_customCommand.ID = field.NewUint(tableName, "id")
	_customCommand.CreatedAt = field.NewTime(tableName, "created_at")
	_customCommand.UpdatedAt = field.NewTime(tableName, "updated_at")
	_customCommand.DeletedAt = field.NewField(tableName, "deleted_at")
	_customCommand.Name = field.NewString(tableName, "name")
	_customCommand.Description = field.NewString(tableName, "description")
	_customCommand.Response = field.NewString(tableName, "response")
	_customCommand.CreatedBy = field.NewString(tableName, "created_by")

	_customCommand.fillFieldMap()

	return _customCommand
}

type customCommand struct {
	customCommandDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Name        field.String
	Description field.String
	Response    field.String
	CreatedBy   field.String

	fieldMap map[string]field.Expr
}

func (c customCommand) Table(newTableName string) *customCommand {
	c.customCommandDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c customCommand) As(alias string) *customCommand {
	c.customCommandDo.DO = *(c.customCommandDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *customCommand) updateTableName(table string) *customCommand {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.Name = field.NewString(table, "name")
	c.Description = field.NewString(table, "description")
	c.Response = field.NewString(table, "response")
	c.CreatedBy = field.NewString(table, "created_by")

	c.fillFieldMap()

	return c
}

func (c *customCommand) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *customCommand) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["name"] = c.Name
	c.fieldMap["description"] = c.Description
	c.fieldMap["response"] = c.Response
	c.fieldMap["created_by"] = c.CreatedBy
}

func (c customCommand) clone(db *gorm.DB) customCommand {
	c.customCommandDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c customCommand) replaceDB(db *gorm.DB) customCommand {
	c.customCommandDo.ReplaceDB(db)
	return c
}

type customCommandDo struct{ gen.DO }

type ICustomCommandDo interface {
	gen.SubQuery
	Debug() ICustomCommandDo
	WithContext(ctx context.Context) ICustomCommandDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICustomCommandDo
	WriteDB() ICustomCommandDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICustomCommandDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICustomCommandDo
	Not(conds ...gen.Condition) ICustomCommandDo
	Or(conds ...gen.Condition) ICustomCommandDo
	Select(conds ...field.Expr) ICustomCommandDo
	Where(conds ...gen.Condition) ICustomCommandDo
	Order(conds ...field.Expr) ICustomCommandDo
	Distinct(cols ...field.Expr) ICustomCommandDo
	Omit(cols ...field.Expr) ICustomCommandDo
	Join(table schema.Tabler, on ...field.Expr) ICustomCommandDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICustomCommandDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICustomCommandDo
	Group(cols ...field.Expr) ICustomCommandDo
	Having(conds ...gen.Condition) ICustomCommandDo
	Limit(limit int) ICustomCommandDo
	Offset(offset int) ICustomCommandDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICustomCommandDo
	Unscoped() ICustomCommandDo
	Create(values ...*models.CustomCommand) error
	CreateInBatches(values []*models.CustomCommand, batchSize int) error
	Save(values ...*models.CustomCommand) error
	First() (*models.CustomCommand, error)
	Take() (*models.CustomCommand, error)
	Last() (*models.CustomCommand, error)
	Find() ([]*models.CustomCommand, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CustomCommand, err error)
	FindInBatches(result *[]*models.CustomCommand, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CustomCommand) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICustomCommandDo
	Assign(attrs ...field.AssignExpr) ICustomCommandDo
	Joins(fields ...field.RelationField) ICustomCommandDo
	Preload(fields ...field.RelationField) ICustomCommandDo
	FirstOrInit() (*models.CustomCommand, error)
	FirstOrCreate() (*models.CustomCommand, error)
	FindByPage(offset int, limit int) (result []*models.CustomCommand, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICustomCommandDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c customCommandDo) Debug() ICustomCommandDo {
	return c.withDO(c.DO.Debug())
}

func (c customCommandDo) WithContext(ctx context.Context) ICustomCommandDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c customCommandDo) ReadDB() ICustomCommandDo {
	return c.Clauses(dbresolver.Read)
}

func (c customCommandDo) WriteDB() ICustomCommandDo {
	return c.Clauses(dbresolver.Write)
}

func (c customCommandDo) Session(config *gorm.Session) ICustomCommandDo {
	return c.withDO(c.DO.Session(config))
}

func (c customCommandDo) Clauses(conds ...clause.Expression) ICustomCommandDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c customCommandDo) Returning(value interface{}, columns ...string) ICustomCommandDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c customCommandDo) Not(conds ...gen.Condition) ICustomCommandDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c customCommandDo) Or(conds ...gen.Condition) ICustomCommandDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c customCommandDo) Select(conds ...field.Expr) ICustomCommandDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c customCommandDo) Where(conds ...gen.Condition) ICustomCommandDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c customCommandDo) Order(conds ...field.Expr) ICustomCommandDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c customCommandDo) Distinct(cols ...field.Expr) ICustomCommandDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c customCommandDo) Omit(cols ...field.Expr) ICustomCommandDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c customCommandDo) Join(table schema.Tabler, on ...field.Expr) ICustomCommandDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c customCommandDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICustomCommandDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c customCommandDo) RightJoin(table schema.Tabler, on ...field.Expr) ICustomCommandDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c customCommandDo) Group(cols ...field.Expr) ICustomCommandDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c customCommandDo) Having(conds ...gen.Condition) ICustomCommandDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c customCommandDo) Limit(limit int) ICustomCommandDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c customCommandDo) Offset(offset int) ICustomCommandDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c customCommandDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICustomCommandDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c customCommandDo) Unscoped() ICustomCommandDo {
	return c.withDO(c.DO.Unscoped())
}

func (c customCommandDo) Create(values ...*models.CustomCommand) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c customCommandDo) CreateInBatches(values []*models.CustomCommand, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c customCommandDo) Save(values ...*models.CustomCommand) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c customCommandDo) First() (*models.CustomCommand, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CustomCommand), nil
	}
}

func (c customCommandDo) Take() (*models.CustomCommand, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CustomCommand), nil
	}
}

func (c customCommandDo) Last() (*models.CustomCommand, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CustomCommand), nil
	}
}

func (c customCommandDo) Find() ([]*models.CustomCommand, error) {
	result, err := c.DO.Find()
	return result.([]*models.CustomCommand), err
}

func (c customCommandDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CustomCommand, err error) {
	buf := make([]*models.CustomCommand, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c customCommandDo) FindInBatches(result *[]*models.CustomCommand, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c customCommandDo) Attrs(attrs ...field.AssignExpr) ICustomCommandDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c customCommandDo) Assign(attrs ...field.AssignExpr) ICustomCommandDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c customCommandDo) Joins(fields ...field.RelationField) ICustomCommandDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c customCommandDo) Preload(fields ...field.RelationField) ICustomCommandDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c customCommandDo) FirstOrInit() (*models.CustomCommand, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CustomCommand), nil
	}
}

func (c customCommandDo) FirstOrCreate() (*models.CustomCommand, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CustomCommand), nil
	}
}

func (c customCommandDo) FindByPage(offset int, limit int) (result []*models.CustomCommand, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c customCommandDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c customCommandDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c customCommandDo) Delete(models ...*models.CustomCommand) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *customCommandDo) withDO(do gen.Dao) *customCommandDo {
	c.DO = *do.(*gen.DO)
	return c
}
