// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q          = new(Query)
	CachedUser *cachedUser
	Sandwich   *sandwich
	Seed       *seed
	Vore       *vore
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	CachedUser = &Q.CachedUser
	Sandwich = &Q.Sandwich
	Seed = &Q.Seed
	Vore = &Q.Vore
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:         db,
		CachedUser: newCachedUser(db, opts...),
		Sandwich:   newSandwich(db, opts...),
		Seed:       newSeed(db, opts...),
		Vore:       newVore(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	CachedUser cachedUser
	Sandwich   sandwich
	Seed       seed
	Vore       vore
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		CachedUser: q.CachedUser.clone(db),
		Sandwich:   q.Sandwich.clone(db),
		Seed:       q.Seed.clone(db),
		Vore:       q.Vore.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		CachedUser: q.CachedUser.replaceDB(db),
		Sandwich:   q.Sandwich.replaceDB(db),
		Seed:       q.Seed.replaceDB(db),
		Vore:       q.Vore.replaceDB(db),
	}
}

type queryCtx struct {
	CachedUser ICachedUserDo
	Sandwich   ISandwichDo
	Seed       ISeedDo
	Vore       IVoreDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		CachedUser: q.CachedUser.WithContext(ctx),
		Sandwich:   q.Sandwich.WithContext(ctx),
		Seed:       q.Seed.WithContext(ctx),
		Vore:       q.Vore.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
